sudo: false
language: node_js
node_js:
  - '14'
branches:
  only:
    - poc/cypress-docker
cache:
  directories:
    - node_modules
install:
  - yarn install
jobs:
  include:
    - stage: Build
    script: yarn build
    - stage: Lint and Test
    name: Unit Tests
    script: yarn test
    name: Lint
    script: yarn lint