version: '3.6'

services:
  root:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3333
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3333'

  core:
    image: 'cypress/included:6.4.0'
    depends_on:
      - root
    environment:
      - CYPRESS_BASE_URL=http://root:3333
    working_dir: /app/packages/synchro-charts
    command: npx cypress run --headless --browser chrome --env updateSnapshots=true
    volumes:
      - .:/app
      # - ./node_modules:/app/node_modules
      # - ./packages/synchro-charts/node_modules:/app/node_modules
      # - ./packages/synchro-charts:/app
      # - ./packages/synchro-charts/cypress:/app/cypress
      # - ./packages/synchro-charts/cypress.json:/app/cypress.json
